language: ruby
rvm:
- 2.2.1
script:
- RAILS_ENV=test bundle exec rake db:migrate
- bundle exec rspec
- bundle exec cucumber
cache: bundler
addons:
  postgresql: '9.3'
notifications:
  email:
    on_success: never
    on_failure: change
  hipchat:
    rooms:
      secure: UAG2L9En3/HjIEjSpXo6gsK7NbqBYKEkifztXtpbImjH84Y9FdH0WiajBeMFbrzLv54rUuz7gJ3WfTt2deoOHmOid/xaxfrunmpY41xCrYsuvM4rp9u/geooVqdC8sIirD8nwD+v0ERCNcX9U/mxWXulzsqyHz8ozfKuu1px0w8=
    notify: true
