language: ruby
rvm:
- 2.2.1
script:
- RAILS_ENV=test bundle exec rake db:migrate
- bundle exec rspec
- bundle exec cucumber
cache: bundler
addons:
  postgresql: '9.3'
notifications:
  email:
    on_success: never
    on_failure: change
  hipchat:
    rooms:
      secure: w205gWStE9mkRjFoTP5ejaMGtcPixjlWW717kOIh3vbRMNeccpfrofEHTEADmG/b3WQudqQdqKU9rpJcOfSU/D/B6gfLG3sIDX7cObkqoNl6JtxC3FHka0coNEqOw0nr8OJs3nNLbE6msu18cO3rMLGku23d7qezh1ID0aYgnrY=
    notify: true